# Q.1. Write an SQL query to find the total quantity sold for each item.
select item_id , sum(quantity) as total_quantity_sold
from orders
group by item_id;


# Q.2. Write an SQL query to display customers who ordered more than one quantity in a single order.
select cust_name , order_id, quantity
from orders
where quantity > 1;


# Q.3. Write an SQL query to calculate the total sales amount generated by each item.
select o.item_id , i.item_name , sum(o.quantity * i.price) as total_sales
from orders as o
join items as i
on o.item_id = i.item_id
group by o.item_id, i.item_name;


# Q.4. Write an SQL query to list all ingredients used in each menu item.
select i.item_name , g.ingredient_name
from recipes as r
join items as i 
on r.item_id = i.item_id
join ingredients as g 
on r.ingredient_id = g.ingredient_id;


# Q.5. Write an SQL query to display staff members working on a specific date.
select s.staff_name , sh.shift_name , r.shift_date
from rota as r
join staff as s 
on r.staff_id = s.staff_id
join shift as sh 
on r.shift_id = sh.shift_id
where r.shift_date = '2024-02-12';


# Q.6. Write an SQL query to find ingredients that are not used in any recipe.
select ingredient_id , ingredient_name
from ingredients
where ingredient_id not in (select distinct ingredient_id from recipes);

# Q.7. Write an SQL query to find the most expensive item in each category.
select category , item_name , price
from items as i
where price = (select max(price) from items where category = i.category);


# Q.8. Write an SQL query to display hour-wise order count.
select hour(created_at) as order_hour , count(*) as total_orders
from orders
group by hour(created_at)
order by order_hour;


# Q.9. Write an SQL query to rank items based on total sales amount.
select i.item_name , sum(o.quantity * i.price) as total_sales ,
rank() over (order by sum(o.quantity * i.price) DESC) as sales_rank
from orders as o
join items as i 
on o.item_id = i.item_id
group by i.item_name;


# Q.10. Write an SQL query to find staff members who worked more than one shift on the same day.
select staff_id , shift_date , count(*) as shift_count
from rota
group by staff_id , shift_date
having COUNT(*) > 1;


# Q.11. Write an SQL query to calculate total ingredient consumption based on all orders.
select i.ingredient_name , sum(o.quantity * r.quantity_required) as total_consumed
from orders as o
join recipes as r 
on o.item_id = r.item_id
join ingredients as i 
on r.ingredient_id = i.ingredient_id
GROUP BY i.ingredient_name;


# Q.12. Write an SQL query to find ingredients where required quantity exceeds available inventory.
select g.ingredient_name , i.quantity_available , sum(o.quantity * r.quantity_required) as total_required
from orders as o
join recipes as r 
on o.item_id = r.item_id
join inventory as i 
on r.ingredient_id = i.ingredient_id
join ingredients as g 
on i.ingredient_id = g.ingredient_id
group by g.ingredient_name , i.quantity_available
having total_required > i.quantity_available;


# Q.13. Write an SQL query to find the top 3 best-selling items based on quantity sold.
with item_sales as (
select i.item_name , sum(o.quantity) as total_quantity
from orders as o
join items as i 
on o.item_id = i.item_id
group by i.item_name
)
select item_name , total_quantity
from item_sales
order by total_quantity DESC
LIMIT 3;


# Q.14. Write an SQL query to create a view that shows daily revenue.
create view daily_revenue as
select date(o.created_at) as sale_date , sum(o.quantity * i.price) as total_revenue
from orders as o
join items as i 
on o.item_id = i.item_id
group by date(o.created_at);


# Q.15. Write a CTE (Common Table Expression) to rank items based on total sales.
with ranked_items as (
select i.item_name , sum(o.quantity * i.price) as total_sales,
rank() over (order by sum(o.quantity * i.price) DESC) as sales_rank
from orders as o
join items as i 
on o.item_id = i.item_id
group by i.item_name
)
select * from ranked_items;
